In [1]:
test = "Hello World!"
print(test)

Hello World!


In [4]:
import numpy as np
one_directional_arr = np.array([10,12])
print(one_directional_arr)

[10 12]


In [1]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\KIIT0001\AppData\Local\Programs\Python\Python311\python.exe
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]


In [6]:
import numpy as np

In [7]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [9]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

In [11]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [13]:
#Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]
