In [1]:
test = "Hello World!"
print(test)

Hello World!


In [3]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\KIIT0001\AppData\Local\Programs\Python\Python311\python.exe
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]


In [4]:
import numpy as np

Python lists are limited in functions and take up more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists.

The array object in NumPy is called `ndraary` meaning 'n-dimensional array'.

In [7]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


There are several ways to create an array in NumPy. We can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array.

In [9]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

In [7]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [13]:
#Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)

# np.arange(start, stop, step)
print(c)

[ 1  4  7 10 13 16 19]


In [8]:
d = np.arange(0, 100, 5)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [11]:
# np.linspace(start, stop, num)
# step = (stop - start) / (num - 1)
a = np.linspace(0, 100, 21)
print(a)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [10]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In np.arange stop is not included but in np.linspace stop is included. np.arange is in int but in np.linspace is in float

In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


# More on NumPy Arrays
One of the advantages of using NumPy is that we can easily create arrays with built-in functions such as:
* `np.ones()` - Returns a new array setting values to one.
* `np.zeros()` - Returns a new array setting values to zero.
* `np.empty()` - Returns a new uninitialized array.
* `np.random.rand()` - Returns a new array with values chosen at random.