In [1]:
test = "Hello World!"
print(test)

Hello World!


In [3]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\KIIT0001\AppData\Local\Programs\Python\Python311\python.exe
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]


In [2]:
import numpy as np

Python lists are limited in functions and take up more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists.

The array object in NumPy is called `ndraary` meaning 'n-dimensional array'.

In [7]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


There are several ways to create an array in NumPy. We can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array.

In [9]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

In [7]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [13]:
#Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)

# np.arange(start, stop, step)
print(c)

[ 1  4  7 10 13 16 19]


In [8]:
d = np.arange(0, 100, 5)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [11]:
# np.linspace(start, stop, num)
# step = (stop - start) / (num - 1)
a = np.linspace(0, 100, 21)
print(a)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [10]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In np.arange stop is not included but in np.linspace stop is included. np.arange is in int but in np.linspace is in float

In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


# More on NumPy Arrays
One of the advantages of using NumPy is that we can easily create arrays with built-in functions such as:
* `np.ones()` - Returns a new array setting values to one.
* `np.zeros()` - Returns a new array setting values to zero.
* `np.empty()` - Returns a new uninitialized array.
* `np.random.rand()` - Returns a new array with values chosen at random.

In [14]:
# Return a new array of shape 3, filled with ones.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [15]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [16]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [17]:
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(5)
print(rand_arr)

[0.04097218 0.00760475 0.14877689 0.74915301 0.30116948]


In [23]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `np.reshape()` you can rearrange elements of the previous array into a new shape.

In [24]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In future assignments, you will need to know how to find the size, dimension and shape of an array. These are all atrributes of a `ndarray` and can be accessed as follows:
- `ndarray.ndim` - Stores the number dimensions of the array.
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- `ndarray.size` - Stores the number of elements in the array.


In [25]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [26]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [27]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

# 3 - Array math operations #
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list, in addition, subtraction and multiplication of Python lists do not work.

In [28]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


## 3.1 - Multiplying vector with a scalar (broadcasting) ##
Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes.

In [35]:
vetor = np.array([1,2])
vetor = vetor * 5
print(vetor)

[ 5 10]


# 4 - Indexing and slicing #
Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays.

## 4.1 - Indexing ##
Let us select specific elements from the arrays as given.

In [1]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [6]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8
